language: python
sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

# virtualenv is a dependency of tox, by default it would install the
# latest version, but virtualenv 14 and above is incompatible with Python 3.2.
install:
  - pip install "virtualenv<14" tox

script:
  - tox -e py

notifications:
  email: false
